[build]
  # Directorio donde se encuentran los archivos construidos
  publish = "dist"
  
  # Comando para construir el proyecto
  command = "npm run build:prod"

[build.environment]
  # Versión de Node.js a usar
  NODE_VERSION = "18"

# Configuración para Single Page Application (SPA)
# Redirige todas las rutas al index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimización
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache para assets estáticos
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # No cachear el HTML principal
    Cache-Control = "no-cache"

# Configuración para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache largo para assets con hash
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración para desarrollo local (opcional)
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 